### ISSUE TITLE
Make `develop` the default branch

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#26] opened 2022-02-01 14:06 UTC

**Comment by IndrajeetPatil** [comment] 2022-02-01 14:07
Duplicate of https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/issues/3

**Comment by PavelBal** [comment] 2022-02-01 14:11
@msevestre I have created the branch. Please change the settings.

**Comment by msevestre** [comment] 2022-02-02 11:19
Will do as soon as all our PR are merged. Otherwise this is going to be a mess

**Comment by IndrajeetPatil** [comment] 2022-02-02 11:38
No more pending PRs for now, so feel free to do this change.

**Comment by msevestre** [comment] 2022-02-02 11:44
done

**Closed by msevestre** 2022-02-02 11:44 UTC
